### ISSUE TITLE
Im trying to get https on it

### ISSUE THREAD

**Issue by joehoeller** [Hulkmaster/advanced-vue-guide#2]
Im trying to get https on it, can you help?

**Comment by Hulkmaster** [comment]
It is not an issue
If you have any questions - ask them at stackoverflow please

after part 4 you need to configure nginx for https
https://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by joehoeller** [comment]
Im aware and cannot use LetsEncrypt, I think its folder paths are the issue.
