### ISSUE TITLE
How to use dev middleware with koa-router?

### ISSUE THREAD

**Issue by haan123** [Hulkmaster/advanced-vue-guide#5]
Hi @Hulkmaster,

My project is using *koa-router* to render the *index.html* file, so how do i implement the code below with koa-router?

`ctx.body = devMiddleware.fileSystem.readFileSync(path.join(clientConfig.output.path, 'index.html'));`

Sorry, i know this is not an issue but i don’t know where to put the question

Thank you!

**Comment by haan123** [comment]
> Hi @Hulkmaster,
> 
> My project is using _koa-router_ to render the _index.html_ file, so how do i implement the code below with koa-router?
> 
> `ctx.body = devMiddleware.fileSystem.readFileSync(path.join(clientConfig.output.path, 'index.html'));`
> 
> Thank you!

**Comment by Hulkmaster** [comment]
Hi, for questions you can use [stackoverflow](https://stackoverflow.com/)
