### ISSUE TITLE
Adding CSS

### ISSUE THREAD

**Issue by vanniekerkalex** [Hulkmaster/advanced-vue-guide#6]
Hi @Hulkmaster 

Great tutorial! Thank you so much, the simplicity and ease of use has made it an incredible tutorial - thank you!

I've run into an issue with the very last bit of the tutorial. Please see image below... do you know how to fix this? I've followed your tutorial verbatim.

Thank you in advance!

![image](https://user-images.githubusercontent.com/38350082/72614625-6b0ba380-393b-11ea-82b1-8a54b3603084.png)

**Comment by Hulkmaster** [comment]
Hey! thanks for submitting an issue

Could you, maybe, create a repo, where i could see the problem?

**Comment by Hulkmaster** [comment]
its not completly clear whats the problem, but i might guess that you created a style tag, but forgot to mention preprocessor lang, or to add webpack loader, for example:

**Comment by Hulkmaster** [comment]
```
      {
        test: /\.styl(us)?$/,
        exclude: /node_modules/,
        use: [
          'vue-style-loader',
          'css-loader',
          'stylus-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [postcssPresetEnv()],
            },
          },
        ],
      },
```

but in that case you must specify lang in style tag

```
<style lang="stylus">
```

**Comment by vanniekerkalex** [comment]
Here is the repo.

https://github.com/vanniekerkalex/vue-guide

Thanks again!

**Comment by Hulkmaster** [comment]
1) you're missing libraries like `postcss-preset-env`
2) because of missing libraries launch an application

if thats the version, which gives you that error, then most likely there is a problem with your docker container - something cached or something else

i would suggest  doing
`git reset --hard origin/master` (will delete any uncommited changed and reset project to last commit)
`docker system prune --volumes -a` (will delete everything docker ever made)

and trying clean install

**Comment by vanniekerkalex** [comment]
The `postcss-preset-env`, was this added during the tutorial? Or do I need to install this on my machine... or do I simply do `yarn add postcss-preset-env` in the root of my repo?

**Comment by vanniekerkalex** [comment]
I've just cloned your repo... and done a `docker-compose -f docker-compose.dev.yml up` for `part4` and it's up and running correctly.

**Comment by vanniekerkalex** [comment]
It seems your `package.json` is quite different than mine, even though I followed your tutorial exactly?

Anyway, thanks for the help... your part4 is a good base for me to work from on new projects. 

If i'm doing dev work, do I use `docker-compose -f docker-compose.dev.yml up` and when I'm done and want to compile for production, would I use `docker-compose up`? 

I'm still a little unsure with this.

**Comment by Hulkmaster** [comment]
i'll try to check the tutorial, it should be working on each step, maybe something was wrnog from the beginning, and somehow i missed that, thanks for reporting!
